#!/bin/bash -e

# Usage: /sbin/wordpress-restore file [file] ...
backupPath="/data/backup"
backupFileSuffix="-wordpress.tar.gz"
backupDbSuffix="-wordpress-db.tar.gz"
databaseFile="database.sql"

for file in "$@"
do
    echo "Processing file ${file}"

    if echo "${file}" | grep -q -e "${backupFileSuffix}"; then
        echo "Restore wordpress files"
        tar -xvzf "${backupPath}/${file}" -C /
        echo "done :)"
    elif echo "${file}" | grep -q -e "${backupDbSuffix}"; then
        echo "Restore wordpress database"
        . /container/service/backup/assets/tool/wordpress-get-db-params

        rm -rf "${databaseFile}" || true
        tar -xvzf "${backupPath}/${file}"

        mysql -u "${databaseUser}" -p"${databasePassword}" --host "${host}" "${database}" < "${databaseFile}"

        rm -rf "${databaseFile}"

        echo "done :)"
    else
      echo "Error: Unknown file type"
    fi
done
